#!/bin/bash

set -e

# https://stackoverflow.com/a/246128/1958900 
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/d-utils

printusage() {
    echo "USAGE: dshell [--socket] [--here] [image-or-container] [container options]"
    exit 1
}


while [ ${1:0:2} == '--' ]; do
  if [ "$1" == "--here" ]; then
      args="$args -v $(pwd):/hostdir -w /hostdir"
  elif [ "$1" == "--socket" ]; then
      args="$args -v /var/run/docker.sock:/var/run/docker.sock"
  else
    printusage
    exit 1
  fi
  shift
done

if [ -z ${1} ]; then
    printusage
    exit 1
fi


objid=$1
dockerargs="$args ${@:2}"
objtype=$(d-classify ${objid})

case "${objtype}" in
    image*)
        launch-shell-in-image "${objid}" ${dockerargs}
        ;;
    stopped*)
        imagename="image-from-${objid}"
        echocmd docker commit "${objid}" ${imagename}
        launch-shell-in-image ${imagename} ${dockerargs}
        ;;
    running*)
        echo "Running 'docker exec ${dockerargs} -it ${objid} sh -c "${BASH_OR_SH}"'"
        docker exec ${dockerargs} -it ${objid} sh -c "${BASH_OR_SH}"
        ;;
    *)
        echo Failed to classify \"${objtype}\"
        exit 1
        ;;
esac
